name: Flake8

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: -1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: find changed files
        id: find_changed_files
        run: echo ::set-output name=changed_files::$(git diff --name-only ${{github.sha}} ${{github.event.pull_request.base.sha}} | tr ' ' '\n' | grep .py | tr '\n' ' ')
      - name: Install flake8
        run: pip install flake8 dlint flake8-bugbear flake8-simplify flake8-debugger flake8-print flake8-pep3101
        if: steps.find_changed_files.outputs.changed_files != ''
      - run: echo ::add-matcher::.github/flake8-matcher.json
        if: steps.find_changed_files.outputs.changed_files != ''
      - name: run flake8
        run: flake8 --exit-zero ${{steps.find_changed_files.outputs.changed_files}}
        if: steps.find_changed_files.outputs.changed_files != ''
